### ISSUE TITLE
[1.16] Recipes missing in JEI

### ISSUE THREAD

**Issue by 016Nojr** [BlakeBr0/MysticalAgriculture#339]
**Describe the bug**
After the latest update, infusing recipes doesnt show up in JEI anymore

**To Reproduce**
Start game, try looking at a seed recipe, infusion is missing.

If you log in to a singleplayer and then log into a multiplayer server it will show up.

**Expected behavior**
Infusion recipe being shown

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Forge: 32.0.108
 - Cucumber: 4.0.2
 - Mystical Agriculture: 4.0.2

**Comment by piesio98** [comment]
same for me
Logs:
https://pastebin.com/H1hVt4dC

Versions:


Minecraft: 1.16.1
Forge: 32.0.108
 jei-1.16.1-7.0.1.10.jar,
jeiintegration_1.16.1-4.0.0.4.jar,
Cucumber-1.16.1-4.0.2.jar,
 MysticalAgradditions-1.16.1-4.0.0.jar, 
 MysticalAgriculture-1.16.1-4.0.2.ja

**Comment by konsaril** [comment]
Same for me
It only shows in Singleplayer or on the LAN Host.


    Minecraft: 1.16.1
    Forge: 32.0.108
    Cucumber: 4.0.2
    Mystical Agriculture: 4.0.2

**Comment by ax-vasquez** [comment]
I too am getting this issue with the latest update.

@konsaril you saved me a lot of pain - didn't know it would still work in single-player. Seems like this is the only workaround for now (for anyone else hitting this).

**Comment by MSandro** [comment]
Same issue here, will there be an fix for 1.16.1? Would be nice

**Comment by SDUBZ** [comment]
@BlakeBr0 can we please get a fix 🙏

**Comment by BlakeBr0** [comment]
I believe this was fixed in the latest version.

**Comment by Swedz** [comment]
Still having this issue on the latest version. Doesn't work in single player either.

**Comment by stanedav** [comment]
Me too, is there any fix for this issue?

**Comment by Swedz** [comment]
> Me too, is there any fix for this issue?

That I know of, no. I tried what others have said in the past here that going in single player makes it work, but I couldn't get that to work. I just had to look up what the infusion recipes are online for now...

Oddly enough, I _was_ able to view the recipes recently until some point that I'm not sure of. My friend that plays on my pack with me on my server doesn't actually have this issue and is able to view all the recipes fine. Not sure how that happened. Maybe we have some setting messed up?

**Comment by stanedav** [comment]
> > Me too, is there any fix for this issue?
> 
> That I know of, no. I tried what others have said in the past here that going in single player makes it work, but I couldn't get that to work. I just had to look up what the infusion recipes are online for now...
> 
> Oddly enough, I _was_ able to view the recipes recently until some point that I'm not sure of. My friend that plays on my pack with me on my server doesn't actually have this issue and is able to view all the recipes fine. Not sure how that happened. Maybe we have some setting messed up?

Actually I play with my GF, I am LAN host and I can see everything. GF is able to search seeds in JEI but recipes are not showing. I tried to make exact copy of my modpack to her PC and no changes

**Comment by stanedav** [comment]
@BlakeBr0 hey bro, I really appreciate your work, do you think, it would be possible to fix this one small bug? :)
